server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file://#{CONFIG_REPO_ABS}   # replaced at runtime via env or use native
          search-paths: configs
          default-label: main

management:
  endpoints:
    web:
      exposure:
        include: health,info
